integration:
  oep:
    connectTimeout: 1
    readTimeout: 1
    external-url: http://localhost:${wiremock.server.port}/external-oepMock
    internal-url: http://localhost:${wiremock.server.port}/internal-oepMock
    username: oep.username
    external-password: oep.client.external.password
    internal-password: oep.client.internal.password
spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.4:///
  flyway:
    enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          schema-generation:
            script:
              append: false
      jakarta:
        persistence:
          schema-generation:
            create-source: metadata
            database:
              action: validate
            scripts:
              action: create
              create-target: target/database/generated-schema.sql
