integration:
  oep:
    connectTimeout: 5
    readTimeout: 30
logbook:
  body-filters:
    json-path: 
      - key: '$.attachments[*].base64Data'
        value: '[base64]'
    x-path:
      - key: '//encodedData[string-length(text()) > 0]'
        value: '[base64]'
logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
resilience4j:
  circuitbreaker:
    instances:
      oep:
        ignoreExceptions: se.sundsvall.dept44.exception.ClientProblem
spring:
  application:
    name: api-web-message-sender
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            database:
              action: validate
  flyway:
    enabled: false
    baseline-on-migrate: true
springdoc:
  swagger-ui:
    operationsSorter: method
