attachment:
  maximum:
    bytesize: 10
integration:
  oep:
    connectTimeout: 10
    readTimeout: 20
    username: oep.client.username
    external-password: oep.client.external.password
    external-url: oep.client.external.url
    internal-password: oep.client.internal.password
    internal-url: oep.client.internal.url
spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.4:///
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          schema-generation:
            script:
              append: false
      jakarta:
        persistence:
          schema-generation:
            create-source: metadata
            database:
              action: update
            scripts:
              action: create
              create-target: target/database/generated-schema.sql
